pipeline {
    agent any
    
     environment {
        ANSIBLE_CONFIG = "${WORKSPACE}/deploy/ansible.cfg" 
    }
    
    parameters {
      string(name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
    }

   

    stages {
        stage('Initial cleanup') {
            steps {
                dir("${WORKSPACE}") {
                    deleteDir() // Clean up the workspace
                }
            }
        }
    

        stage('Checkout SCM') {
            steps {
                git branch: 'main', url: 'https://github.com/GenetH/ansible-config-mgt.git'
            }
        }

        stage('Prepare Ansible For Execution') {
        steps {
        script {
            def cfgPath = "${WORKSPACE}/deploy/ansible.cfg"
            sh """
            if ! grep -q 'roles_path=${WORKSPACE}/roles' ${cfgPath}; then
                echo 'roles_path=${WORKSPACE}/roles' >> ${cfgPath}
            fi
            """
        }
        }
        }

        stage('Test SSH Connection') {
            steps {
                sshagent(['private-key']) { 
                    sh 'ssh -o StrictHostKeyChecking=no -i /home/ubuntu/.ssh/id_rsa.pem ubuntu@172.31.42.10 exit'
                }
            }
        }

        stage('Run Ansible playbook') {
            steps {
                sshagent(['private-key']) {
                    ansiblePlaybook(
                        playbook: "${WORKSPACE}/playbooks/site.yml",
                        inventory: "${WORKSPACE}/inventory/${inventory}.yml",
                        become: true,
                        credentialsId: 'private-key'

                    )
                }
            }
        }
        stage('Clean Workspace after build') {
            steps {
                cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, deleteDirs: true)
            }
        }
    }
}
