---
- name: Install necessary packages
  ansible.builtin.apt:
    name:
      - gnupg2
      - wget
      - unzip
    state: present
    update_cache: yes


- name: Download JFrog GPG key
  ansible.builtin.get_url:
    url: "https://releases.jfrog.io/artifactory/api/gpg/key/public"
    dest: /usr/share/keyrings/jfrog.gpg
    mode: '0644'

- name: Add the JFrog Artifactory repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/jfrog.gpg] https://releases.jfrog.io/artifactory/artifactory-debs focal main"
    state: present
    
- name: Update the repository cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install JFrog Artifactory OSS
  ansible.builtin.apt:
    name: jfrog-artifactory-oss
    state: present

- name: Start and enable Artifactory service
  ansible.builtin.service:
    name: artifactory
    state: started
    enabled: yes
